### PR TITLE
build(deps): migrate to @fastify/error

### PR DESCRIPTION
**Pull request by Fdawgs**
`fastify-error` has been deprecated as the module has been moved to `@fastify/error`

### CODE REVIEW

**Comment by jonnydgreen** [comment]
Thanks @Fdawgs - looks like an unrelated dependency upgrade has meant the checks are out of date - hence, the CI failure. I'll update this branch later today so they pass, unless you'd like to do it of course :)

**Comment by mcollina** [comment]
@Fdawgs could you rebase?

**Comment by Fdawgs** [comment]
rebased into the wrong fork branch, either way it's there.

**Review by jonnydgreen — APPROVED** [review]
LGTM

**Pull request merged**
